repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/perltidy/perltidy
  rev: '20221112.03'
  hooks:
    - id: perltidy
- repo: https://github.com/scop/pre-commit-perlcritic
  rev: v1.146-1
  hooks:
    - id: perlcritic
- repo: local
  hooks:
    - id: perlimports
      name: perlimports
      language: perl
      entry: perlimports -i
      args: ["lib"]
      types: [perl]
