repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: no-commit-to-branch
      args: ['--branch', 'main']
- repo: https://github.com/henryykt/pre-commit-perl
  rev: v0.0.5
  hooks:
    - id: perltidy
    - id: perlcritic
    - id: perlimports
